[monitor:///logs/auth_service.log]
index = main
sourcetype = log4j:auth
disabled = 0
crcSalt = <SOURCE>

[monitor:///logs/inventory_service.log]
index = main
sourcetype = log4j:inventory
disabled = 0
crcSalt = <SOURCE>

[monitor:///logs/status_service.log]
index = main
sourcetype = log4j:status
disabled = 0
crcSalt = <SOURCE>
