services:
  # ZONE 1: NIPRNet (The Office - Entry Point)
  logistics-portal:
    build: ./src/logistics-portal
    container_name: logistics-portal
    ports:
      - "80:8080"
    volumes:
      - ./flags:/flags:ro
    networks:
      - public-net
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: always

  # ZONE 2: The "Bridge" (Air-Gap Maintenance Terminal)
  maintenance-terminal:
    build: ./src/maintenance-terminal
    container_name: maintenance-terminal
    networks:
      - public-net
      - avionics-net
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - logistics-portal
      - serial-bus
    restart: always

  # ZONE 3: The Jet (Target - Air-Gapped)
  serial-bus:
    build: ./src/serial-bus
    volumes:
      - ./src/serial-bus:/app
    ports:
      # We still expose UDP locally for testing attacks,
      # but in the 'challenge' flow, the portal can't reach this.
      - "5001:5001/udp"
    networks:
      - avionics-net
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

networks:
  public-net:
    driver: bridge
  avionics-net:
    driver: bridge
    internal: true # Disables external access (no internet for the jet)